version: '3'

services:
  dog-server:
    image: nginx
    container_name: 'dog-container'
    volumes:
      - ./dog-server:/usr/share/nginx/html
    ports:
      - 7000:80
  
  cat-server:
    image: nginx
    container_name: 'cat-container'
    volumes:
      - ./cat-server:/usr/share/nginx/html
    ports:
      - 7001:80

  database:
    image: mysql:5.7
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    ports:
      - "${LOCAL_DB_PORT}:3306"
    restart: always
    container_name: "${PRODUCTION_NAME}_db"
    environment:
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      
  wordpress:
      depends_on:
        - database
      image: wordpress:php7.3-fpm
      container_name: "${PRODUCTION_NAME}_wordpress"
      expose:
        - "9000"
      restart: always
      volumes:
            - ./public:/var/www/html
      environment:
        WORDPRESS_DB_HOST: database:3306
        WORDPRESS_DB_PASSWORD: wordpress
  wordmove:
      tty: true
      depends_on:
        - wordpress
      image: welaika/wordmove
      restart: on-failure:5
      container_name: "${PRODUCTION_NAME}_wordmove"
      volumes:
        - ./config:/home/
        - ./public:/var/www/html
        - ${HOME}/.ssh:/home/.ssh

      environment:
        LOCAL_SERVER_PORT: "9000"
        PRODUCTION_URL: "${PRODUCTION_URL}"
        PRODUCTION_DIR_PATH: "${PRODUCTION_DIR_PATH}"
        PRODUCTION_DB_NAME: "${PRODUCTION_DB_NAME}"
        PRODUCTION_DB_USER: "${PRODUCTION_DB_USER}"
        PRODUCTION_DB_PASSWORD: "${PRODUCTION_DB_PASSWORD}"
        PRODUCTION_DB_HOST: "${PRODUCTION_DB_HOST}"
        PRODUCTION_DB_PORT: "${PRODUCTION_DB_PORT}"
        PRODUCTION_SSH_HOST: "${PRODUCTION_SSH_HOST}"
        PRODUCTION_SSH_USER: "${PRODUCTION_SSH_USER}"
        PRODUCTION_SSH_PORT: "${PRODUCTION_SSH_PORT}"

  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html
    ports:
      - 80:80
      
    extra_hosts:
      - "host.docker.internal:192.168.10.107"
      
    depends_on:
      - wordpress # wordpress起動後でないとnginxがnot foundで落ちる

